name: Build rpm and deb packages
on:
  push:
    branches:
      - main
jobs:
  build_rpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build RPM Package
        run: |
          cd rpm_package_build
          docker build -t rpm_build .
          docker run --name rpm_build_container rpm_build
        shell: bash

      - name: Extract RPM package
        run: |
          mkdir rpm_package
          docker cp rpm_build_container:/root/rpmbuild/RPMS/noarch/psycopg-3.1.12-1.noarch.rpm ./rpm_package
        working-directory: .

      - name: Upload RPM Package
        uses: actions/upload-artifact@v2
        with:
          name: psycopg-3.1.12.noarch.rpm
          path: ./rpm_package
  build_deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build DEB Package
        run: |
          cd deb_package_build
          docker build -t deb_build .
          docker run --name deb_build_container deb_build
        shell: bash

      - name: Extract DEB package
        run: |
          mkdir deb_package
          docker cp deb_build_container:./psycopg_3.1.12_all.deb ./deb_package
        working-directory: .

      - name: Upload DEB Package
        uses: actions/upload-artifact@v2
        with:
          name: psycopg_3.1.12_all.deb
          path: ./deb_package